homeassistant:
  enabled: false
mqtt:
  server: mqtt://mosquitto:1883
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyUSB0
  adapter: ember
  baudrate: 115200
  rtscts: false
frontend:
  enabled: true
  port: 8080
experimental:
  new_api: true
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  report_payload_formatter: attribute
  network_key:
    - 72
    - 107
    - 221
    - 249
    - 13
    - 142
    - 230
    - 136
    - 100
    - 51
    - 155
    - 196
    - 80
    - 125
    - 130
    - 0
device_options: {}
version: 5
devices:
  '0xa4c13809fbba5246':
    friendly_name: '0xa4c13809fbba5246'
  '0xa4c1388e501b0447':
    friendly_name: Датчик качества воздуха
  '0xa4c1382e284d2eeb':
    friendly_name: Датчик C1382EEB
